import SingleEffect from "./SingleEffect";
import "../styles/OtherEffects.scss";

import {
  GiGreenhouse as GreenhouseIcon,
  GiWildfires as FireIcon,
  GiMoonOrbit as DarknessIcon,
} from "react-icons/gi";
import { BsFillCloudRainHeavyFill as RainIcon } from "react-icons/bs";
import { FaEarthEurope } from "react-icons/fa6";

const DistalEffects = () => {
  const distalEffects = [
    {
      name: "Acid Rain",
      icon: <RainIcon />,
      description:
        "After a significant asteroid impact, the release of gases and particles into the atmosphere can lead to the formation of acid rain. This occurs when water vapor combines with these atmospheric pollutants, producing acidic precipitation. Acid rain can have detrimental effects on ecosystems, damaging vegetation, aquatic life, and soil quality.",
    },
    {
      name: "Global Distribution of Ejecta",
      icon: <FaEarthEurope />,
      description:
        "Ejecta refers to the material thrown out during the impact. The global distribution of ejecta involves the dispersion of these materials, such as rocks and debris, across the Earth's surface. This can have widespread consequences, affecting landscapes, ecosystems, and even contributing to the formation of impact craters.",
    },
    {
      name: "Global Wildfires",
      icon: <FireIcon />,
      description:
        "The intense heat generated by an asteroid impact can ignite widespread wildfires. This is particularly true if the impact occurs in an area with abundant vegetation. The combination of heat and ejected materials can trigger fires over large geographical areas, further impacting ecosystems and contributing to environmental challenges.",
    },
    {
      name: "Global Darkness",
      icon: <DarknessIcon />,
      description:
        "The massive release of dust and debris into the atmosphere following an asteroid impact can obscure sunlight, leading to a phenomenon known as 'impact winter' or 'global darkness'. Reduced sunlight penetration can disrupt photosynthesis, affect temperature patterns, and lead to a prolonged period of darkness, impacting both flora and fauna.",
    },
    {
      name: "Greenhouse Effects",
      icon: <GreenhouseIcon />,
      description:
        "The release of gases, including water vapor and carbon dioxide, during an impact can contribute to greenhouse effects. These gases trap heat in the Earth's atmosphere, leading to an increase in overall temperatures. This warming effect can have long-term consequences for climate patterns, weather systems, and the overall stability of ecosystems.",
    },
  ];
  return (
    <article className="distal-effects-container">
      <h2>Distal effects</h2>
      <p>
        After those, a myriad of related, distal problems would emerge, things
        that would affect us way more than the immediate effects...
      </p>

      <div className="distal-effects-display">
        {distalEffects.map((el, i) => (
          <SingleEffect effectData={el} key={i} />
        ))}
      </div>

      <p className>
        Each of these distal effects underscores the far-reaching and
        interconnected consequences of a significant asteroid impact,
        emphasizing the importance of understanding and mitigating potential
        impacts on Earth.
      </p>
    </article>
  );
};

export default DistalEffects;
